<?php

/**
 * PluginPriorityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPriorityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPriorityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPriority');
    }
}