<?php

/**
 * PluginTasksTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTasksTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTasksTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTasks');
    }
}
